document.write("<h1>Site Map</h1>");
document.write("<ul>");
	document.write("<li><a href='index.html'>Home</a></li>");
		document.write("<li><a href='profile.html'>Profile</a></li>");
		document.write("<li><a href='project.html'>Work</a></li>");
		document.write("<li><a href='fun.html'>Fun</a></li>");
		document.write("<li><a href='album.html' >Photos</a></li>");
		document.write("<li><a href='ubuntu.html'>Ubuntu stuff</a></li>");
		document.write("<li><a href='links.html'>Links</a></li>");
		document.write("<li><a href='contact.html'>Contact</a></li>");
	document.write("</ul>");
document.write("<a href='http://github.com/the-codebreaker' target='_blank'><img style='position: absolute; top: 0; left: 0; border: 0;' src='img/git.png' alt='Fork me on GitHub'></a>");
