document.write("<h1>Site Map</h1>");
document.write("<ul>");
	document.write("<li><a href='index.html'>Home</a></li>");
		document.write("<li><a href='profile.html'>Profile</a></li>");
		document.write("<li><a href='project.html'>Work</a></li>");
		document.write("<li><a href='fun.html'>Fun</a></li>");
		document.write("<li><a href='./album/album.html' target='_blank'>Images</a></li>");
		document.write("<li><a href='ubuntu.html'>Ubuntu stuff</a></li>");
		document.write("<li><a href='miscellaneous.html'>Miscellaneous</a></li>");
		document.write("<li><a href='contact.html'>Contact</a></li>");
	document.write("</ul>");
